.TH "_GDOUBLE4" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GDOUBLE4 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_GDOUBLE4\fP ()"
.br
.ti -1c
.RI "\fB_GDOUBLE4\fP (\fBGDOUBLE\fP _x, \fBGDOUBLE\fP _y, \fBGDOUBLE\fP _z, \fBGDOUBLE\fP _w)"
.br
.ti -1c
.RI "\fB_GDOUBLE4\fP (const \fBGDOUBLE\fP *pArray)"
.br
.ti -1c
.RI "\fB_GDOUBLE4\fP & \fBoperator=\fP (const \fB_GDOUBLE4\fP &d4)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGDOUBLE\fP \fBx\fP"
.br
.ti -1c
.RI "\fBGDOUBLE\fP \fBy\fP"
.br
.ti -1c
.RI "\fBGDOUBLE\fP \fBz\fP"
.br
.ti -1c
.RI "\fBGDOUBLE\fP \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
4개의 double형 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "_GDOUBLE4::_GDOUBLE4 ()\fC [inline]\fP"

.SS "_GDOUBLE4::_GDOUBLE4 (\fBGDOUBLE\fP _x, \fBGDOUBLE\fP _y, \fBGDOUBLE\fP _z, \fBGDOUBLE\fP _w)\fC [inline]\fP"

.SS "_GDOUBLE4::_GDOUBLE4 (const \fBGDOUBLE\fP * pArray)"

.SH "Member Function Documentation"
.PP 
.SS "\fB_GDOUBLE4\fP & _GDOUBLE4::operator= (const \fB_GDOUBLE4\fP & d4)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGDOUBLE\fP _GDOUBLE4::w"

.SS "\fBGDOUBLE\fP _GDOUBLE4::x"

.SS "\fBGDOUBLE\fP _GDOUBLE4::y"

.SS "\fBGDOUBLE\fP _GDOUBLE4::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
