.TH "_GDOUBLE3" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GDOUBLE3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_GDOUBLE3\fP ()"
.br
.ti -1c
.RI "\fB_GDOUBLE3\fP (\fBGDOUBLE\fP _x, \fBGDOUBLE\fP _y, \fBGDOUBLE\fP _z)"
.br
.ti -1c
.RI "\fB_GDOUBLE3\fP (const \fBGDOUBLE\fP *pArray)"
.br
.ti -1c
.RI "\fB_GDOUBLE3\fP & \fBoperator=\fP (const \fB_GDOUBLE3\fP &d3)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGDOUBLE\fP \fBx\fP"
.br
.ti -1c
.RI "\fBGDOUBLE\fP \fBy\fP"
.br
.ti -1c
.RI "\fBGDOUBLE\fP \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
3개의 double형 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "_GDOUBLE3::_GDOUBLE3 ()\fC [inline]\fP"

.SS "_GDOUBLE3::_GDOUBLE3 (\fBGDOUBLE\fP _x, \fBGDOUBLE\fP _y, \fBGDOUBLE\fP _z)\fC [inline]\fP"

.SS "_GDOUBLE3::_GDOUBLE3 (const \fBGDOUBLE\fP * pArray)"

.SH "Member Function Documentation"
.PP 
.SS "\fB_GDOUBLE3\fP & _GDOUBLE3::operator= (const \fB_GDOUBLE3\fP & d3)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGDOUBLE\fP _GDOUBLE3::x"

.SS "\fBGDOUBLE\fP _GDOUBLE3::y"

.SS "\fBGDOUBLE\fP _GDOUBLE3::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
