.TH "_GDOUBLE2" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GDOUBLE2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_GDOUBLE2\fP ()"
.br
.ti -1c
.RI "\fB_GDOUBLE2\fP (\fBGDOUBLE\fP _x, \fBGDOUBLE\fP _y)"
.br
.ti -1c
.RI "\fB_GDOUBLE2\fP (const \fBGDOUBLE\fP *pArray)"
.br
.ti -1c
.RI "\fB_GDOUBLE2\fP & \fBoperator=\fP (const \fB_GDOUBLE2\fP &d2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGDOUBLE\fP \fBx\fP"
.br
.ti -1c
.RI "\fBGDOUBLE\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
2개의 double형 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "_GDOUBLE2::_GDOUBLE2 ()\fC [inline]\fP"

.SS "_GDOUBLE2::_GDOUBLE2 (\fBGDOUBLE\fP _x, \fBGDOUBLE\fP _y)\fC [inline]\fP"

.SS "_GDOUBLE2::_GDOUBLE2 (const \fBGDOUBLE\fP * pArray)"

.SH "Member Function Documentation"
.PP 
.SS "\fB_GDOUBLE2\fP & _GDOUBLE2::operator= (const \fB_GDOUBLE2\fP & d2)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGDOUBLE\fP _GDOUBLE2::x"

.SS "\fBGDOUBLE\fP _GDOUBLE2::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
