.TH "_GFLOAT4" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GFLOAT4 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_GFLOAT4\fP ()"
.br
.ti -1c
.RI "\fB_GFLOAT4\fP (\fBGFLOAT\fP _x, \fBGFLOAT\fP _y, \fBGFLOAT\fP _z, \fBGFLOAT\fP _a)"
.br
.ti -1c
.RI "\fB_GFLOAT4\fP (const \fBGFLOAT\fP *pArray)"
.br
.ti -1c
.RI "\fB_GFLOAT4\fP & \fBoperator=\fP (const \fB_GFLOAT4\fP &f4)"
.br
.ti -1c
.RI "\fB_GFLOAT4\fP & \fBoperator=\fP (const \fBGFLOAT3\fP &f3)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGFLOAT\fP \fBx\fP"
.br
.ti -1c
.RI "\fBGFLOAT\fP \fBy\fP"
.br
.ti -1c
.RI "\fBGFLOAT\fP \fBz\fP"
.br
.ti -1c
.RI "\fBGFLOAT\fP \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
4개의 float형 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "_GFLOAT4::_GFLOAT4 ()\fC [inline]\fP"

.SS "_GFLOAT4::_GFLOAT4 (\fBGFLOAT\fP _x, \fBGFLOAT\fP _y, \fBGFLOAT\fP _z, \fBGFLOAT\fP _a)\fC [inline]\fP"

.SS "\fBGIMPLEMENT_OPERATOR_EQUAL_END\fP _GFLOAT4::_GFLOAT4 (const \fBGFLOAT\fP * pArray)"

.SH "Member Function Documentation"
.PP 
.SS "\fB_GFLOAT4\fP & _GFLOAT4::operator= (const \fB_GFLOAT4\fP & f4)"

.SS "\fB_GFLOAT4\fP & _GFLOAT4::operator= (const \fBGFLOAT3\fP & f3)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGFLOAT\fP _GFLOAT4::a"

.SS "\fBGFLOAT\fP _GFLOAT4::x"

.SS "\fBGFLOAT\fP _GFLOAT4::y"

.SS "\fBGFLOAT\fP _GFLOAT4::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
