.TH "CAboutDlg" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAboutDlg \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CDialogEx, and CDialogEx\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBIDD\fP = IDD_ABOUTBOX }"
.br
.ti -1c
.RI "enum { \fBIDD\fP = IDD_ABOUTBOX }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAboutDlg\fP ()"
.br
.ti -1c
.RI "\fBCAboutDlg\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDoDataExchange\fP (CDataExchange *pDX)"
.br
.ti -1c
.RI "virtual void \fBDoDataExchange\fP (CDataExchange *pDX)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIDD \fP\fP
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIDD \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAboutDlg::CAboutDlg ()"

.SS "CAboutDlg::CAboutDlg ()"

.SH "Member Function Documentation"
.PP 
.SS "virtual void CAboutDlg::DoDataExchange (CDataExchange * pDX)\fC [protected]\fP, \fC [virtual]\fP"

.SS "void CAboutDlg::DoDataExchange (CDataExchange * pDX)\fC [protected]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
