.TH "CChildFrame" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CChildFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ChildFrm\&.h>\fP
.PP
Inherits CMDIChildWnd, and CMDIChildWndEx\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCChildFrame\fP ()"
.br
.ti -1c
.RI "virtual BOOL \fBPreCreateWindow\fP (CREATESTRUCT &cs)"
.br
.ti -1c
.RI "virtual \fB~CChildFrame\fP ()"
.br
.ti -1c
.RI "\fBCChildFrame\fP ()"
.br
.ti -1c
.RI "virtual BOOL \fBPreCreateWindow\fP (CREATESTRUCT &cs)"
.br
.ti -1c
.RI "virtual \fB~CChildFrame\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "afx_msg void \fBOnFilePrint\fP ()"
.br
.ti -1c
.RI "afx_msg void \fBOnFilePrintPreview\fP ()"
.br
.ti -1c
.RI "afx_msg void \fBOnUpdateFilePrintPreview\fP (CCmdUI *pCmdUI)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CChildFrame::CChildFrame ()"

.SS "CChildFrame::~CChildFrame ()\fC [virtual]\fP"

.SS "CChildFrame::CChildFrame ()"

.SS "virtual CChildFrame::~CChildFrame ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CChildFrame::OnFilePrint ()\fC [protected]\fP"

.SS "void CChildFrame::OnFilePrintPreview ()\fC [protected]\fP"

.SS "void CChildFrame::OnUpdateFilePrintPreview (CCmdUI * pCmdUI)\fC [protected]\fP"

.SS "virtual BOOL CChildFrame::PreCreateWindow (CREATESTRUCT & cs)\fC [virtual]\fP"

.SS "BOOL CChildFrame::PreCreateWindow (CREATESTRUCT & cs)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
