.TH "CDlgG3DView" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDlgG3DView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DlgG3DView\&.h>\fP
.PP
Inherits CDialogEx\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitG3DView\fP ()"
.br
.ti -1c
.RI "\fBCDlgG3DView\fP (CWnd *pParent=NULL)"
.br
.ti -1c
.RI "virtual \fB~CDlgG3DView\fP ()"
.br
.ti -1c
.RI "afx_msg void \fBOnButtonG3dviewDialog\fP ()"
.br
.ti -1c
.RI "virtual BOOL \fBOnInitDialog\fP ()"
.br
.ti -1c
.RI "afx_msg void \fBOnPaint\fP ()"
.br
.ti -1c
.RI "afx_msg void \fBOnSize\fP (UINT nType, int cx, int cy)"
.br
.ti -1c
.RI "afx_msg void \fBOnBnClickedButtonDraw\fP ()"
.br
.ti -1c
.RI "afx_msg BOOL \fBOnMouseWheel\fP (UINT nFlags, short zDelta, CPoint pt)"
.br
.ti -1c
.RI "afx_msg void \fBOnMouseMove\fP (UINT nFlags, CPoint point)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDoDataExchange\fP (CDataExchange *pDX)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDlgG3DView::CDlgG3DView (CWnd * pParent = \fCNULL\fP)"

.SS "CDlgG3DView::~CDlgG3DView ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CDlgG3DView::DoDataExchange (CDataExchange * pDX)\fC [protected]\fP, \fC [virtual]\fP"

.SS "void CDlgG3DView::InitG3DView ()"

.SS "void CDlgG3DView::OnBnClickedButtonDraw ()"

.SS "void CDlgG3DView::OnButtonG3dviewDialog ()"

.SS "BOOL CDlgG3DView::OnInitDialog ()\fC [virtual]\fP"

.SS "void CDlgG3DView::OnMouseMove (UINT nFlags, CPoint point)"

.SS "BOOL CDlgG3DView::OnMouseWheel (UINT nFlags, short zDelta, CPoint pt)"

.SS "void CDlgG3DView::OnPaint ()"

.SS "void CDlgG3DView::OnSize (UINT nType, int cx, int cy)"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
