.TH "CG3DDB" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CG3DDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G3DDB\&.h>\fP
.PP
Inherited by \fBCGSpaceManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddObject\fP (\fBCGObjectBase\fP *pObject)"
.br
.ti -1c
.RI "\fBCGObjectManager\fP & \fBGetObjectManager\fP ()"
.br
.ti -1c
.RI "const \fBCGObjectManager\fP & \fBGetObjectManager\fP () const "
.br
.ti -1c
.RI "\fBCGPropertyManager\fP & \fBGetPropertyManager\fP ()"
.br
.ti -1c
.RI "\fBCGFontManager\fP * \fBGetFontManager\fP ()"
.br
.ti -1c
.RI "\fBCG3DDB\fP ()"
.br
.ti -1c
.RI "\fB~CG3DDB\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
Database 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CG3DDB::CG3DDB ()"

.SS "CG3DDB::~CG3DDB ()"

.SH "Member Function Documentation"
.PP 
.SS "void CG3DDB::AddObject (\fBCGObjectBase\fP * pObject)"

.IP "\(bu" 2
Object를 DB에 추가한다\&.
.IP "\(bu" 2
Object가 유효한 ID를 가지고, 속성을 가지기 위해서는 DB에 등록되어야 한다\&. 
.PP

.SS "\fBCGFontManager\fP * CG3DDB::GetFontManager ()"

.SS "\fBCGObjectManager\fP & CG3DDB::GetObjectManager ()"

.SS "const \fBCGObjectManager\fP & CG3DDB::GetObjectManager () const"

.SS "\fBCGPropertyManager\fP & CG3DDB::GetPropertyManager ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
