.TH "CG3DViewLayer" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CG3DViewLayer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <G3DViewLayer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetDB\fP (\fBCG3DDB\fP *pDB)"
.br
.ti -1c
.RI "\fBCG3DDB\fP * \fBGetDB\fP ()"
.br
.ti -1c
.RI "void \fBSetName\fP (const CAtlString &strName)"
.br
.ti -1c
.RI "CAtlString \fBGetName\fP () const "
.br
.ti -1c
.RI "\fBCG3DViewLayer\fP ()"
.br
.ti -1c
.RI "\fB~CG3DViewLayer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
view layer 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGIMPLEMENT_OPERATOR_COPY_END\fP CG3DViewLayer::CG3DViewLayer ()"

.SS "CG3DViewLayer::~CG3DViewLayer ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBCG3DDB\fP * CG3DViewLayer::GetDB ()"

.SS "CAtlString CG3DViewLayer::GetName () const"

.SS "void CG3DViewLayer::SetDB (\fBCG3DDB\fP * pDB)"

.SS "void CG3DViewLayer::SetName (const CAtlString & strName)"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
