.TH "CGDCTargetView" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGDCTargetView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GDCTargetView\&.h>\fP
.PP
Inherited by \fBCGDCDirectX11TargetView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBGINT32\fP & \fBGetClienWidth\fP () const "
.br
.ti -1c
.RI "void \fBSetClienWidth\fP (const \fBGINT32\fP &ClientWidth)"
.br
.ti -1c
.RI "const \fBGINT32\fP & \fBGetClienHeight\fP () const "
.br
.ti -1c
.RI "void \fBSetClientHeight\fP (const \fBGINT32\fP &ClienHeight)"
.br
.ti -1c
.RI "\fBCGDCTargetView\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGDCTargetView\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBGINT32\fP \fBmClientWidth\fP"
.br
.ti -1c
.RI "\fBGINT32\fP \fBmClientHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
DC가 그려지는 View에 대한 정보 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGDCTargetView::CGDCTargetView ()"

.SS "CGDCTargetView::~CGDCTargetView ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBGINT32\fP & CGDCTargetView::GetClienHeight () const"

.SS "const \fBGINT32\fP & CGDCTargetView::GetClienWidth () const"

.SS "void CGDCTargetView::SetClientHeight (const \fBGINT32\fP & ClienHeight)"

.SS "void CGDCTargetView::SetClienWidth (const \fBGINT32\fP & ClientWidth)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGINT32\fP CGDCTargetView::mClientHeight\fC [protected]\fP"

.SS "\fBGINT32\fP CGDCTargetView::mClientWidth\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
