.TH "CGDCTargetViewInitData" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGDCTargetViewInitData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GDCTargetViewInitData\&.h>\fP
.PP
Inherited by \fBCG3DViewInitData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetWnd\fP (HWND hWnd)"
.br
.ti -1c
.RI "HWND \fBGetWnd\fP () const "
.br
.ti -1c
.RI "\fBGDEFINE_OPERATOR_COPY\fP (\fBCGDCTargetViewInitData\fP)"
.br
.ti -1c
.RI "\fBCGDCTargetViewInitData\fP ()"
.br
.ti -1c
.RI "\fB~CGDCTargetViewInitData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
CDCTargetView를 초기화하기 위한 data class 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGDCTargetViewInitData::CGDCTargetViewInitData ()"

.SS "CGDCTargetViewInitData::~CGDCTargetViewInitData ()"

.SH "Member Function Documentation"
.PP 
.SS "CGDCTargetViewInitData::GDEFINE_OPERATOR_COPY (\fBCGDCTargetViewInitData\fP)"

.SS "HWND CGDCTargetViewInitData::GetWnd () const"

.SS "void CGDCTargetViewInitData::SetWnd (HWND hWnd)"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
