.TH "CGDCDirectX11TargetView" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGDCDirectX11TargetView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GDCDirectX11TargetView\&.h>\fP
.PP
Inherits \fBCGDCTargetView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCGDCDirectX11TargetView\fP ()"
.br
.ti -1c
.RI "virtual \fB~CGDCDirectX11TargetView\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCGDCDirectX11\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
DirectX11 DC가 그려지는 view
.IP "\(bu" 2
맴버 변수만 갖고 있는다\&. 실제 동작은 DC에서 처리한다\&. 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGDCDirectX11TargetView::CGDCDirectX11TargetView ()"

.SS "CGDCDirectX11TargetView::~CGDCDirectX11TargetView ()\fC [virtual]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBCGDCDirectX11\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
