.TH "CGEngineLauncherDoc" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGEngineLauncherDoc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GEngineLauncherDoc\&.h>\fP
.PP
Inherits CDocument\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual BOOL \fBOnNewDocument\fP ()"
.br
.ti -1c
.RI "virtual void \fBSerialize\fP (CArchive &ar)"
.br
.ti -1c
.RI "virtual \fB~CGEngineLauncherDoc\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCG3DDB\fP * \fBm_pG3DB\fP"
.br
.ti -1c
.RI "\fBCG3DDB\fP * \fBm_pG3DBPreview\fP"
.br
.ti -1c
.RI "\fBCGDCDirectX11\fP * \fBm_pGDC\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCGEngineLauncherDoc\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGEngineLauncherDoc::CGEngineLauncherDoc ()\fC [protected]\fP"

.SS "CGEngineLauncherDoc::~CGEngineLauncherDoc ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "BOOL CGEngineLauncherDoc::OnNewDocument ()\fC [virtual]\fP"

.SS "void CGEngineLauncherDoc::Serialize (CArchive & ar)\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCG3DDB\fP* CGEngineLauncherDoc::m_pG3DB"

.SS "\fBCG3DDB\fP* CGEngineLauncherDoc::m_pG3DBPreview"

.SS "\fBCGDCDirectX11\fP* CGEngineLauncherDoc::m_pGDC"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
