.TH "CGExchangeBase" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGExchangeBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GExchangeBase\&.h>\fP
.PP
Inherited by \fBCGExchangeDxf\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCGExchangeBase\fP (void)"
.br
.ti -1c
.RI "virtual \fB~CGExchangeBase\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
exchange의 기본 클래스 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGExchangeBase::CGExchangeBase (void)"

.SS "CGExchangeBase::~CGExchangeBase (void)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
