.TH "CGIDManager" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGIDManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GIDManager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitCurrentID\fP ()"
.br
.ti -1c
.RI "\fBGID\fP \fBGetCurrentID\fP ()"
.br
.ti -1c
.RI "\fBCGIDManager\fP ()"
.br
.ti -1c
.RI "\fB~CGIDManager\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
ID를 관리한다\&. 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGIDManager::CGIDManager ()"

.SS "CGIDManager::~CGIDManager ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBGID\fP CGIDManager::GetCurrentID ()"

.IP "\(bu" 2
ID를 하나 사용한다\&. 
.PP

.SS "void CGIDManager::InitCurrentID ()"

.IP "\(bu" 2
현재 ID를 초기화 한다\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
