.TH "CGLauncherDoc" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGLauncherDoc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GLauncherDoc\&.h>\fP
.PP
Inherits CDocument\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual BOOL \fBOnNewDocument\fP ()"
.br
.ti -1c
.RI "virtual void \fBSerialize\fP (CArchive &ar)"
.br
.ti -1c
.RI "virtual \fB~CGLauncherDoc\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCG3DDB\fP * \fBm_pG3DB\fP"
.br
.ti -1c
.RI "\fBCG3DDB\fP * \fBm_pG3DBPreview\fP"
.br
.ti -1c
.RI "\fBCG3DDB\fP * \fBm_pG3DBTemp\fP"
.br
.ti -1c
.RI "\fBCGDCDirectX11\fP * \fBm_pGDC\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCGLauncherDoc\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGLauncherDoc::CGLauncherDoc ()\fC [protected]\fP"

.SS "CGLauncherDoc::~CGLauncherDoc ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "BOOL CGLauncherDoc::OnNewDocument ()\fC [virtual]\fP"

.SS "void CGLauncherDoc::Serialize (CArchive & ar)\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCG3DDB\fP* CGLauncherDoc::m_pG3DB"

.SS "\fBCG3DDB\fP* CGLauncherDoc::m_pG3DBPreview"

.SS "\fBCG3DDB\fP* CGLauncherDoc::m_pG3DBTemp"

.SS "\fBCGDCDirectX11\fP* CGLauncherDoc::m_pGDC"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
