.TH "CGQuadTreeElement" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CGQuadTreeElement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GQuadTree\&.hpp>\fP
.PP
Inherits \fBQuadTreeOccupant\fP\&.
.PP
Inherited by \fBCGSpaceQuadtreeElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBoundary\fP (const \fBAABB\fP &rc)"
.br
.ti -1c
.RI "\fBCGQuadTreeElement\fP ()"
.br
.ti -1c
.RI "\fBCGQuadTreeElement\fP (const \fBCGQuadTreeElement\fP &d)"
.br
.ti -1c
.RI "virtual \fB~CGQuadTreeElement\fP (void)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CGQuadTreeElement::CGQuadTreeElement ()\fC [inline]\fP"

.SS "CGQuadTreeElement::CGQuadTreeElement (const \fBCGQuadTreeElement\fP & d)\fC [inline]\fP"

.SS "virtual CGQuadTreeElement::~CGQuadTreeElement (void)\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CGQuadTreeElement::SetBoundary (const \fBAABB\fP & rc)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
