.TH "D:/MyProject/Trunk/Engine/GEngine/Src/G3D/G3DDefine.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/G3D/G3DDefine.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBG3D_DRAWING_CALLBACK\fP) (\fBCGDC\fP *, const \fBCGObjectBase\fP *)"
.br
.ti -1c
.RI "typedef \fBCG3DActionBase\fP *(* \fBG3D_CREATING_ACTION_CALLBACK\fP) ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBCG3DActionBase\fP*(* G3D_CREATING_ACTION_CALLBACK) ()"

.IP "\(bu" 2
action을 create하는 callback 정의 
.PP

.SS "typedef void(* G3D_DRAWING_CALLBACK) (\fBCGDC\fP *, const \fBCGObjectBase\fP *)"

.IP "\(bu" 2
drawing callback 정의 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
