.TH "D:/MyProject/Trunk/Engine/GEngine/Src/G3D/G3DView.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/G3D/G3DView.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'atltypes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCG3DView\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGVIEWLAYER_MAIN\fP   \fBGNOTRANS\fP('MAIN')"
.br
.ti -1c
.RI "#define \fBGVIEWLAYER_PREVIEW\fP   \fBGNOTRANS\fP('PREVIEW')"
.br
.ti -1c
.RI "#define \fBGVIEWLAYER_TEMP\fP   \fBGNOTRANS\fP('TEMP')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GVIEWLAYER_MAIN   \fBGNOTRANS\fP('MAIN')"

.SS "#define GVIEWLAYER_PREVIEW   \fBGNOTRANS\fP('PREVIEW')"

.SS "#define GVIEWLAYER_TEMP   \fBGNOTRANS\fP('TEMP')"

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
