.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GIDManager.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GIDManager.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGIDManager\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGNONE_ID\fP   0"
.br
.ti -1c
.RI "#define \fBGFIRST_ID\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GFIRST_ID   1"

.SS "#define GNONE_ID   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
