.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GMath.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GMath.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGMath\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFrustrumPlane\fP { \fBeFrustrumPlaneTop\fP, \fBeFrustrumPlaneBottom\fP, \fBeFrustrumPlaneNear\fP, \fBeFrustrumPlaneFar\fP, \fBeFrustrumPlaneLeft\fP, \fBeFrustrumPlaneRight\fP, \fBeFrustrumPlaneCount\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFrustrumPlane\fP"

.IP "\(bu" 2
frustrum plane 
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIeFrustrumPlaneTop \fP\fP
.TP
\fB\fIeFrustrumPlaneBottom \fP\fP
.TP
\fB\fIeFrustrumPlaneNear \fP\fP
.TP
\fB\fIeFrustrumPlaneFar \fP\fP
.TP
\fB\fIeFrustrumPlaneLeft \fP\fP
.TP
\fB\fIeFrustrumPlaneRight \fP\fP
.TP
\fB\fIeFrustrumPlaneCount \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
