.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GShell.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GShell.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGShell\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWUNKNOWN\fP   0"
.br
.ti -1c
.RI "#define \fBW9XFIRST\fP   1"
.br
.ti -1c
.RI "#define \fBW95\fP   1"
.br
.ti -1c
.RI "#define \fBW95SP1\fP   2"
.br
.ti -1c
.RI "#define \fBW95OSR2\fP   3"
.br
.ti -1c
.RI "#define \fBW98\fP   4"
.br
.ti -1c
.RI "#define \fBW98SP1\fP   5"
.br
.ti -1c
.RI "#define \fBW98SE\fP   6"
.br
.ti -1c
.RI "#define \fBWME\fP   7"
.br
.ti -1c
.RI "#define \fBW9XLAST\fP   99"
.br
.ti -1c
.RI "#define \fBWNTFIRST\fP   101"
.br
.ti -1c
.RI "#define \fBWNT351\fP   101"
.br
.ti -1c
.RI "#define \fBWNT4\fP   102"
.br
.ti -1c
.RI "#define \fBW2K\fP   103"
.br
.ti -1c
.RI "#define \fBWXP\fP   104"
.br
.ti -1c
.RI "#define \fBWVISTA\fP   105"
.br
.ti -1c
.RI "#define \fBW7\fP   106"
.br
.ti -1c
.RI "#define \fBWNTLAST\fP   199"
.br
.ti -1c
.RI "#define \fBWCEFIRST\fP   201"
.br
.ti -1c
.RI "#define \fBWCE\fP   201"
.br
.ti -1c
.RI "#define \fBWCELAST\fP   299"
.br
.ti -1c
.RI "#define \fBWUNKNOWNSTR\fP   _T('unknown Windows version')"
.br
.ti -1c
.RI "#define \fBW95STR\fP   _T('Windows 95')"
.br
.ti -1c
.RI "#define \fBW95SP1STR\fP   _T('Windows 95 SP1')"
.br
.ti -1c
.RI "#define \fBW95OSR2STR\fP   _T('Windows 95 OSR2')"
.br
.ti -1c
.RI "#define \fBW98STR\fP   _T('Windows 98')"
.br
.ti -1c
.RI "#define \fBW98SP1STR\fP   _T('Windows 98 SP1')"
.br
.ti -1c
.RI "#define \fBW98SESTR\fP   _T('Windows 98 SE')"
.br
.ti -1c
.RI "#define \fBWMESTR\fP   _T('Windows ME')"
.br
.ti -1c
.RI "#define \fBWNT351STR\fP   _T('Windows NT 3\&.51')"
.br
.ti -1c
.RI "#define \fBWNT4STR\fP   _T('Windows NT 4')"
.br
.ti -1c
.RI "#define \fBW2KSTR\fP   _T('Windows 2000')"
.br
.ti -1c
.RI "#define \fBWXPSTR\fP   _T('Windows XP')"
.br
.ti -1c
.RI "#define \fBWVISTASTR\fP   _T('Windows Vista')"
.br
.ti -1c
.RI "#define \fBW7STR\fP   _T('Windows 7')"
.br
.ti -1c
.RI "#define \fBWCESTR\fP   _T('Windows CE')"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define W2K   103"

.SS "#define W2KSTR   _T('Windows 2000')"

.SS "#define W7   106"

.SS "#define W7STR   _T('Windows 7')"

.SS "#define W95   1"

.SS "#define W95OSR2   3"

.SS "#define W95OSR2STR   _T('Windows 95 OSR2')"

.SS "#define W95SP1   2"

.SS "#define W95SP1STR   _T('Windows 95 SP1')"

.SS "#define W95STR   _T('Windows 95')"

.SS "#define W98   4"

.SS "#define W98SE   6"

.SS "#define W98SESTR   _T('Windows 98 SE')"

.SS "#define W98SP1   5"

.SS "#define W98SP1STR   _T('Windows 98 SP1')"

.SS "#define W98STR   _T('Windows 98')"

.SS "#define W9XFIRST   1"

.SS "#define W9XLAST   99"

.SS "#define WCE   201"

.SS "#define WCEFIRST   201"

.SS "#define WCELAST   299"

.SS "#define WCESTR   _T('Windows CE')"

.SS "#define WME   7"

.SS "#define WMESTR   _T('Windows ME')"

.SS "#define WNT351   101"

.SS "#define WNT351STR   _T('Windows NT 3\&.51')"

.SS "#define WNT4   102"

.SS "#define WNT4STR   _T('Windows NT 4')"

.SS "#define WNTFIRST   101"

.SS "#define WNTLAST   199"

.SS "#define WUNKNOWN   0"

.SS "#define WUNKNOWNSTR   _T('unknown Windows version')"

.SS "#define WVISTA   105"

.SS "#define WVISTASTR   _T('Windows Vista')"

.SS "#define WXP   104"

.SS "#define WXPSTR   _T('Windows XP')"

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
