.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GTriangleStrip.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/GTriangleStrip.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCGTriangleStrip\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef CAtlArray< \fBCGPoint3D\fP > \fBTriangleStripPoint\fP"
.br
.ti -1c
.RI "typedef CAtlArray< \fBGUINT32\fP > \fBTriangleStripIndex\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef CAtlArray<\fBGUINT32\fP> \fBTriangleStripIndex\fP"

.SS "typedef CAtlArray<\fBCGPoint3D\fP> \fBTriangleStripPoint\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
