.TH "GVERTEX" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GVERTEX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGDEFINE_OPERATOR_COPY_NOVIRTUAL\fP (\fBGVERTEX\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGFLOAT3\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBGFLOAT4\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBGUINT\fP \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.IP "\(bu" 2
vertex buffer에 사용될 vertex의 타입 
.PP
\fBTodo\fP
.RS 4

.RE
.PP
- vertex type 을 정의한다\&. 
.PP

.SH "Member Function Documentation"
.PP 
.SS "GVERTEX::GDEFINE_OPERATOR_COPY_NOVIRTUAL (\fBGVERTEX\fP)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGFLOAT4\fP GVERTEX::color"

.SS "\fBGUINT\fP GVERTEX::id"

.SS "\fBGFLOAT3\fP GVERTEX::pos"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
