.TH "p2t::SweepContext::EdgeEvent" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2t::SweepContext::EdgeEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sweep_context\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdgeEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEdge\fP * \fBconstrained_edge\fP"
.br
.ti -1c
.RI "bool \fBright\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "p2t::SweepContext::EdgeEvent::EdgeEvent ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEdge\fP* p2t::SweepContext::EdgeEvent::constrained_edge"

.SS "bool p2t::SweepContext::EdgeEvent::right"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
