.TH "p2t::SweepContext::Basin" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2t::SweepContext::Basin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sweep_context\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasin\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBleft_node\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBbottom_node\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBright_node\fP"
.br
.ti -1c
.RI "double \fBwidth\fP"
.br
.ti -1c
.RI "bool \fBleft_highest\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "p2t::SweepContext::Basin::Basin ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void p2t::SweepContext::Basin::Clear ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* p2t::SweepContext::Basin::bottom_node"

.SS "bool p2t::SweepContext::Basin::left_highest"

.SS "\fBNode\fP* p2t::SweepContext::Basin::left_node"

.SS "\fBNode\fP* p2t::SweepContext::Basin::right_node"

.SS "double p2t::SweepContext::Basin::width"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
