.TH "p2t::AdvancingFront" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2t::AdvancingFront \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <advancing_front\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdvancingFront\fP (\fBNode\fP &\fBhead\fP, \fBNode\fP &\fBtail\fP)"
.br
.ti -1c
.RI "\fB~AdvancingFront\fP ()"
.br
.ti -1c
.RI "\fBNode\fP * \fBhead\fP ()"
.br
.ti -1c
.RI "void \fBset_head\fP (\fBNode\fP *node)"
.br
.ti -1c
.RI "\fBNode\fP * \fBtail\fP ()"
.br
.ti -1c
.RI "void \fBset_tail\fP (\fBNode\fP *node)"
.br
.ti -1c
.RI "\fBNode\fP * \fBsearch\fP ()"
.br
.ti -1c
.RI "void \fBset_search\fP (\fBNode\fP *node)"
.br
.ti -1c
.RI "\fBNode\fP * \fBLocateNode\fP (const double &x)"
.br
.RI "\fILocate insertion point along advancing front\&. \fP"
.ti -1c
.RI "\fBNode\fP * \fBLocatePoint\fP (const \fBPoint\fP *point)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "p2t::AdvancingFront::AdvancingFront (\fBNode\fP & head, \fBNode\fP & tail)"

.SS "p2t::AdvancingFront::~AdvancingFront ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP * p2t::AdvancingFront::head ()\fC [inline]\fP"

.SS "\fBNode\fP * p2t::AdvancingFront::LocateNode (const double & x)"

.PP
Locate insertion point along advancing front\&. 
.SS "\fBNode\fP * p2t::AdvancingFront::LocatePoint (const \fBPoint\fP * point)"

.SS "\fBNode\fP * p2t::AdvancingFront::search ()\fC [inline]\fP"

.SS "void p2t::AdvancingFront::set_head (\fBNode\fP * node)\fC [inline]\fP"

.SS "void p2t::AdvancingFront::set_search (\fBNode\fP * node)\fC [inline]\fP"

.SS "void p2t::AdvancingFront::set_tail (\fBNode\fP * node)\fC [inline]\fP"

.SS "\fBNode\fP * p2t::AdvancingFront::tail ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
