.TH "p2t::Edge" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2t::Edge \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shapes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdge\fP (\fBPoint\fP &p1, \fBPoint\fP &p2)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP * \fBp\fP"
.br
.ti -1c
.RI "\fBPoint\fP * \fBq\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "p2t::Edge::Edge (\fBPoint\fP & p1, \fBPoint\fP & p2)\fC [inline]\fP"

.PP
Constructor\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBPoint\fP* p2t::Edge::p"

.SS "\fBPoint\fP * p2t::Edge::q"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
