.TH "p2t::Sweep" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2t::Sweep \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sweep\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTriangulate\fP (\fBSweepContext\fP &tcx)"
.br
.ti -1c
.RI "\fB~Sweep\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "p2t::Sweep::~Sweep ()"
Destructor - clean up memory 
.SH "Member Function Documentation"
.PP 
.SS "void p2t::Sweep::Triangulate (\fBSweepContext\fP & tcx)"
\fBTriangulate\fP
.PP
\fBParameters:\fP
.RS 4
\fItcx\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
