.TH "p2t::Node" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p2t::Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <advancing_front\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (\fBPoint\fP &p)"
.br
.ti -1c
.RI "\fBNode\fP (\fBPoint\fP &p, \fBTriangle\fP &t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP * \fBpoint\fP"
.br
.ti -1c
.RI "\fBTriangle\fP * \fBtriangle\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBprev\fP"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "p2t::Node::Node (\fBPoint\fP & p)\fC [inline]\fP"

.SS "p2t::Node::Node (\fBPoint\fP & p, \fBTriangle\fP & t)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBNode\fP* p2t::Node::next"

.SS "\fBPoint\fP* p2t::Node::point"

.SS "\fBNode\fP* p2t::Node::prev"

.SS "\fBTriangle\fP* p2t::Node::triangle"

.SS "double p2t::Node::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
