.TH "Point2i" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point2i \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GQuadTree\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint2i\fP (const int &X, const int &Y)"
.br
.ti -1c
.RI "\fBPoint2i\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBPoint2i\fP &other) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Point2i::Point2i (const int & X, const int & Y)\fC [inline]\fP"

.SS "Point2i::Point2i ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool Point2i::operator== (\fBPoint2i\fP & other) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int Point2i::x"

.SS "int Point2i::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
