.TH "QuadTreeOccupant" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuadTreeOccupant \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GQuadTree\&.hpp>\fP
.PP
Inherited by \fBCGQuadTreeElement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBQuadTreeOccupant\fP & \fBoperator=\fP (const \fBQuadTreeOccupant\fP &d)"
.br
.ti -1c
.RI "\fBQuadTreeOccupant\fP ()"
.br
.ti -1c
.RI "\fBQuadTreeOccupant\fP (const \fBQuadTreeOccupant\fP &d)"
.br
.ti -1c
.RI "virtual \fB~QuadTreeOccupant\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpQuadTreeNode\fP"
.br
.ti -1c
.RI "void * \fBpQuadTree\fP"
.br
.ti -1c
.RI "\fBAABB\fP \fBaabb\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QuadTreeOccupant::QuadTreeOccupant ()\fC [inline]\fP"

.SS "QuadTreeOccupant::QuadTreeOccupant (const \fBQuadTreeOccupant\fP & d)\fC [inline]\fP"

.SS "virtual QuadTreeOccupant::~QuadTreeOccupant ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBQuadTreeOccupant\fP& QuadTreeOccupant::operator= (const \fBQuadTreeOccupant\fP & d)\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBAABB\fP QuadTreeOccupant::aabb"

.SS "void* QuadTreeOccupant::pQuadTree"

.SS "void* QuadTreeOccupant::pQuadTreeNode"


.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
