.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GLauncher/resource.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GLauncher/resource.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIDD_ABOUTBOX\fP   100"
.br
.ti -1c
.RI "#define \fBIDP_OLE_INIT_FAILED\fP   100"
.br
.ti -1c
.RI "#define \fBIDR_MAINFRAME\fP   128"
.br
.ti -1c
.RI "#define \fBIDR_GLauncherTYPE\fP   130"
.br
.ti -1c
.RI "#define \fBID_WINDOW_MANAGER\fP   131"
.br
.ti -1c
.RI "#define \fBIDD_DIALOG_SPACE_VIEW\fP   310"
.br
.ti -1c
.RI "#define \fBIDC_STATIC_GLAUNCHER_SPACE_VIEW\fP   1000"
.br
.ti -1c
.RI "#define \fBIDC_EDIT_GLAUNCHER_OBJECT_NUM\fP   1001"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_GLAUNCHER_DRAW_OBJECT\fP   1002"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_GLAUNCHER_REALTIME_DRAW_OBJECT\fP   1003"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_GLAUNCHER_DELETE_ALL\fP   1004"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_GLAUNCHER_DELETE_ALL2\fP   1005"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_GLAUNCHER_SELECT\fP   1005"
.br
.ti -1c
.RI "#define \fBIDC_BUTTON_GLAUNCHER_UNSELECT\fP   1006"
.br
.ti -1c
.RI "#define \fBIDC_EDIT_SPACE_NUM\fP   1008"
.br
.ti -1c
.RI "#define \fBIDC_EDIT_OBJECT_NUM\fP   1009"
.br
.ti -1c
.RI "#define \fBIDC_COMBO_GLAUNCHER_OBJECT_TYPE\fP   1010"
.br
.ti -1c
.RI "#define \fBIDC_EDIT_VISIBLE_SPACE_NUM\fP   1011"
.br
.ti -1c
.RI "#define \fBIDC_CHECK1\fP   1012"
.br
.ti -1c
.RI "#define \fBIDC_CHECK_VIEW_SPACE\fP   1012"
.br
.ti -1c
.RI "#define \fBID_CONTROL_SPACEVIEW\fP   32771"
.br
.ti -1c
.RI "#define \fBID_DRAW_POINT\fP   32772"
.br
.ti -1c
.RI "#define \fBID_DRAW_LINE\fP   32773"
.br
.ti -1c
.RI "#define \fBID_DRAW_CYLINDER\fP   32774"
.br
.ti -1c
.RI "#define \fBID_DRAW_BOX\fP   32775"
.br
.ti -1c
.RI "#define \fBID_DRAW_SPHERE\fP   32776"
.br
.ti -1c
.RI "#define \fBID_DRAW_CIRCLE\fP   32777"
.br
.ti -1c
.RI "#define \fBID_DRAW_GRID\fP   32778"
.br
.ti -1c
.RI "#define \fBID_DRAW_TRIANGLE\fP   32779"
.br
.ti -1c
.RI "#define \fBID_EDIT_ELETE\fP   32780"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETE\fP   32781"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETEALL\fP   32782"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETE_ALL\fP   32783"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETEALLEACH\fP   32784"
.br
.ti -1c
.RI "#define \fBID_EDIT_ELETE32785\fP   32785"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETE100OBJECTSEACH\fP   32786"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETE_100_OBJECTS\fP   32787"
.br
.ti -1c
.RI "#define \fBID_EDIT_DELETE100OBJECTS\fP   32788"
.br
.ti -1c
.RI "#define \fBID_ACTION_DRAWLINE\fP   32789"
.br
.ti -1c
.RI "#define \fBID_ACTION_ENDACTION\fP   32790"
.br
.ti -1c
.RI "#define \fBID_SELECT_SELECT100OBJECTS\fP   32791"
.br
.ti -1c
.RI "#define \fBID_SELECT_SELECT100OBJECTSEACH\fP   32792"
.br
.ti -1c
.RI "#define \fBID_SELECT_UNSELECTALL\fP   32793"
.br
.ti -1c
.RI "#define \fBID_ACTION_ID\fP   32794"
.br
.ti -1c
.RI "#define \fBID_ACTION_SELECT\fP   32795"
.br
.ti -1c
.RI "#define \fBID_DRAW_POLYLINE3D\fP   32796"
.br
.ti -1c
.RI "#define \fBID_SELECT_DYNAMICHIGHLIGHT\fP   32797"
.br
.ti -1c
.RI "#define \fBID_ACTION_DRAWCIRCLE\fP   32798"
.br
.ti -1c
.RI "#define \fBID_DRAW_COMPOUNDOBJECT\fP   32799"
.br
.ti -1c
.RI "#define \fBID_EDIT_MOVE\fP   32800"
.br
.ti -1c
.RI "#define \fBID_ACTION_COPY\fP   32801"
.br
.ti -1c
.RI "#define \fBID_ACTION_ROTATE2D\fP   32802"
.br
.ti -1c
.RI "#define \fBID_ACTION_SCALE\fP   32803"
.br
.ti -1c
.RI "#define \fBID_EXCHANGE_DXF\fP   32804"
.br
.ti -1c
.RI "#define \fBID_DXF_IMPORT\fP   32805"
.br
.ti -1c
.RI "#define \fBID_DXF_EXPORT\fP   32806"
.br
.ti -1c
.RI "#define \fBID_DRAW_TEXT\fP   32807"
.br
.ti -1c
.RI "#define \fBID_DRAW_FACE\fP   32808"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ID_ACTION_COPY   32801"

.SS "#define ID_ACTION_DRAWCIRCLE   32798"

.SS "#define ID_ACTION_DRAWLINE   32789"

.SS "#define ID_ACTION_ENDACTION   32790"

.SS "#define ID_ACTION_ID   32794"

.SS "#define ID_ACTION_ROTATE2D   32802"

.SS "#define ID_ACTION_SCALE   32803"

.SS "#define ID_ACTION_SELECT   32795"

.SS "#define ID_CONTROL_SPACEVIEW   32771"

.SS "#define ID_DRAW_BOX   32775"

.SS "#define ID_DRAW_CIRCLE   32777"

.SS "#define ID_DRAW_COMPOUNDOBJECT   32799"

.SS "#define ID_DRAW_CYLINDER   32774"

.SS "#define ID_DRAW_FACE   32808"

.SS "#define ID_DRAW_GRID   32778"

.SS "#define ID_DRAW_LINE   32773"

.SS "#define ID_DRAW_POINT   32772"

.SS "#define ID_DRAW_POLYLINE3D   32796"

.SS "#define ID_DRAW_SPHERE   32776"

.SS "#define ID_DRAW_TEXT   32807"

.SS "#define ID_DRAW_TRIANGLE   32779"

.SS "#define ID_DXF_EXPORT   32806"

.SS "#define ID_DXF_IMPORT   32805"

.SS "#define ID_EDIT_DELETE   32781"

.SS "#define ID_EDIT_DELETE100OBJECTS   32788"

.SS "#define ID_EDIT_DELETE100OBJECTSEACH   32786"

.SS "#define ID_EDIT_DELETE_100_OBJECTS   32787"

.SS "#define ID_EDIT_DELETE_ALL   32783"

.SS "#define ID_EDIT_DELETEALL   32782"

.SS "#define ID_EDIT_DELETEALLEACH   32784"

.SS "#define ID_EDIT_ELETE   32780"

.SS "#define ID_EDIT_ELETE32785   32785"

.SS "#define ID_EDIT_MOVE   32800"

.SS "#define ID_EXCHANGE_DXF   32804"

.SS "#define ID_SELECT_DYNAMICHIGHLIGHT   32797"

.SS "#define ID_SELECT_SELECT100OBJECTS   32791"

.SS "#define ID_SELECT_SELECT100OBJECTSEACH   32792"

.SS "#define ID_SELECT_UNSELECTALL   32793"

.SS "#define ID_WINDOW_MANAGER   131"

.SS "#define IDC_BUTTON_GLAUNCHER_DELETE_ALL   1004"

.SS "#define IDC_BUTTON_GLAUNCHER_DELETE_ALL2   1005"

.SS "#define IDC_BUTTON_GLAUNCHER_DRAW_OBJECT   1002"

.SS "#define IDC_BUTTON_GLAUNCHER_REALTIME_DRAW_OBJECT   1003"

.SS "#define IDC_BUTTON_GLAUNCHER_SELECT   1005"

.SS "#define IDC_BUTTON_GLAUNCHER_UNSELECT   1006"

.SS "#define IDC_CHECK1   1012"

.SS "#define IDC_CHECK_VIEW_SPACE   1012"

.SS "#define IDC_COMBO_GLAUNCHER_OBJECT_TYPE   1010"

.SS "#define IDC_EDIT_GLAUNCHER_OBJECT_NUM   1001"

.SS "#define IDC_EDIT_OBJECT_NUM   1009"

.SS "#define IDC_EDIT_SPACE_NUM   1008"

.SS "#define IDC_EDIT_VISIBLE_SPACE_NUM   1011"

.SS "#define IDC_STATIC_GLAUNCHER_SPACE_VIEW   1000"

.SS "#define IDD_ABOUTBOX   100"

.SS "#define IDD_DIALOG_SPACE_VIEW   310"

.SS "#define IDP_OLE_INIT_FAILED   100"

.SS "#define IDR_GLauncherTYPE   130"

.SS "#define IDR_MAINFRAME   128"

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
