.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GLauncher/stdafx.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GLauncher/stdafx.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'targetver\&.h'\fP
.br
\fC#include <afxwin\&.h>\fP
.br
\fC#include <afxext\&.h>\fP
.br
\fC#include <afxdisp\&.h>\fP
.br
\fC#include <afxdtctl\&.h>\fP
.br
\fC#include <afxcmn\&.h>\fP
.br
\fC#include 'atlstr\&.h'\fP
.br
\fC#include 'GCommon\&.h'\fP
.br
\fC#include 'GDB\&.h'\fP
.br
\fC#include 'GExchange\&.h'\fP
.br
\fC#include 'G3D\&.h'\fP
.br
\fC#include <afxcontrolbars\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_SECURE_ATL\fP   1"
.br
.ti -1c
.RI "#define \fBVC_EXTRALEAN\fP"
.br
.ti -1c
.RI "#define \fB_ATL_CSTRING_EXPLICIT_CONSTRUCTORS\fP"
.br
.ti -1c
.RI "#define \fB_AFX_ALL_WARNINGS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _AFX_ALL_WARNINGS"

.SS "#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS"

.SS "#define _SECURE_ATL   1"

.SS "#define VC_EXTRALEAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
