.TH "D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/sweep/sweep_context.h" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/MyProject/Trunk/Engine/GEngine/Src/GCommon/sweep/sweep_context.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstddef>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBp2t::SweepContext\fP"
.br
.ti -1c
.RI "struct \fBp2t::SweepContext::Basin\fP"
.br
.ti -1c
.RI "struct \fBp2t::SweepContext::EdgeEvent\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBp2t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBp2t::kAlpha\fP = 0\&.3"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GEngine from the source code\&.
