.TH "todo" 3 "Sat Dec 26 2015" "Version v0.1" "GEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBCG3DSpaceView::RegenOnlyObject\fP (const CAtlString &strViewLayerName, const \fBCGObjectBase\fP &object)\fP" 1c
.IP "\(bu" 2
space를 이동하는 경우 object의 buffer item ID가 바뀐다\&. 그 순간 object 와 buffer item id와 연결이 깨진다\&.\&. 동기화를 잘 해줘야 할듯\&.\&.!!!!! ( 심각!!! )  
.PP
.IP "\fBClass \fBCGArc3D\fP \fP" 1c
.IP "\(bu" 2
구현해야함\&.  
.PP
.IP "\fBMember \fBCGCamera::ZoomAll\fP (const \fBCGCube\fP &cubeBoundary)\fP" 1c
.IP "\(bu" 2
2D 평면만 동작한다\&.  
.PP
.IP "\fBMember \fBCGDCDirectX11::CalcWorldCoordinateByWindowCoordinate\fP (\fBCGDCTargetView\fP *pDCTargetView, const CPoint &ptWindow)\fP" 1c
.IP "\(bu" 2
3D view에서는 테스트가 안됨\&. 평면뷰 기준으로 계산하고 있음\&.  
.PP
.IP "\fBMember \fBCGObjectFace::GetAllStripVertexListIndexByPrimitiveTopology\fP (GOUT CAtlArray< GVERTEX > &arrVertex, GOUT CAtlArray< GUINT32 > &arrIndex) const \fP" 1c
.IP "\(bu" 2
구현해야함  
.PP
.IP "\fBMember \fBCGPropertyManager::SetObjectColor\fP (GINOUT \fBCGObjectBase\fP *pObj, const GINT32 &iObjectCount, const \fBCGColor\fP &color)\fP" 1c
.IP "\(bu" 2
속도 체크 해야함(매우 중요)
.IP "  \(bu" 4
line 200만개 설정
.IP "    \(bu" 6
GBOOL \fBSetObjectColor(GINOUT CGObjectBase *pObj, const GINT32 &iObjectCount, const CGColor &color)\fP; : 14초
.IP "    \(bu" 6
GBOOL \fBSetObjectColor(GINOUT CGObjectBase *pObj, const CGColor &color)\fP; : 8초  
.PP

.PP

.PP
.IP "\fBMember \fBCGSpace::UpdateSimpleShape\fP (const \fBCGObjectBase\fP &object)\fP" 1c
.IP "\(bu" 2
나중에\&.\&. 아주 나중에 개략형상을 이미지화 해보면 어떨까 싶음\&.\&.\&.
.IP "\(bu" 2
현재는 그냥 마지막에 추가된 객체의 색으로 뿌릴것임\&.\&.  
.PP
.IP "\fBMember \fBCGSpaceManager::CreateOptimizedSpaceForOBject\fP (const \fBCGObjectBase\fP &object)\fP" 1c
.IP "\(bu" 2
고민중\&.\&.\&.
.IP "  \(bu" 4
space의 크기를 동적으로 커지게 할지?(quadtree를 빠르게 갱신할 수 있어야 한다\&. 될까)
.IP "  \(bu" 4
space의 크기를 고정시킬지?(quadtree를 갱신하지 않아도 되지만, space의 개수가 너무 많이 늘어날 수 있다) - 우선선정 : 기본 크기를 좀 키워서 과도한 개수늚을 최소화한다\&.  
.PP

.PP
.IP "\fBMember \fBCGSpaceManager::FindSpaceInView\fP (GOUT CAtlArray< CGSpace * > &arrSpace)\fP" 1c
.IP "\(bu" 2
코딩해야함(현재 모든 space가 보이는 것으로 한다)  
.PP
.IP "\fBMember \fBCGSpaceManager::FindSpaceOutOfView\fP (GOUT CAtlArray< CGSpace * > &arrSpace)\fP" 1c
.IP "\(bu" 2
코딩해야함(현재 모든 space가 보이는 것으로 한다)  
.PP
.IP "\fBClass \fBGVERTEX\fP \fP" 1c
.IP "\(bu" 2
vertex별로 색상을 가질 수 있도록 해야 하는지 검토해서 적용한다\&. 
.PP
.PP

